"$schema" = "./node_modules/wrangler/config-schema.json"

name = "ginja-ai-prototype-shell"
main = "apps/cloudflare-worker/src/index.ts"
compatibility_date = "2026-06-08"

[assets]
directory = "./dist/apps/shell"
binding = "ASSETS"
not_found_handling = "single-page-application"
